### ISSUE TITLE
Can you please update IoU attack code for OTB100

### ISSUE THREAD

**Issue by nkv1995** [VISION-SJTU/IoUattack#3]
Dear @joshuajss

Please  update the code in https://github.com/VISION-SJTU/IoUattack/blob/main/pysot/tools/test_IoU_attack.py with OTB100 

Moreover, can you mention the speed of the tracker with and without attack? I see on V100 GPU that the tracker running at around 1 FPS on VOT2018 after the attack for SiamRPN++.

**Comment by joshuajss** [comment]
The method for attacking on OTB100 is the same as VOT datasets except for the reinitialization.

The attack speed is limited as the query of models is required. I do not recommend using the attack speed on VOT2018 since more failures involved fewer frames. 

The attack speed on OTB is about 2.26fps on an NVIDIA RTX 2080Ti GPU. Hope this will help you.

**Comment by nkv1995** [comment]
Thank you for the response.

If I understand correctly, the OTB100 dataset which has roughly 600 frames per average. So, it takes 600/2.26 =  265 seconds (4.5 mins) on average per video. The entire dataset takes ~7.5 hours. 

Is this the expected time as per your opinion? the reason I'm asking is I'm trying to run the attack on other models on siamcar, siamban, but not sure if I have enough resources to run the experiments.

**Comment by joshuajss** [comment]
Yes. The attack also depends on the original speed of trackers and does not involve too many computations.

**Comment by nkv1995** [comment]
thanks a lot.
